### ISSUE TITLE
Move "add url"-feature to the bottom

### ISSUE THREAD

**Issue by wilpjan** [ggirou/yet-another-jenkins-notifier#16]
First things first: Great Plugin.
I recommend moving the "add url"-feature to the bottom or to the options. It uses almost 20% of the available space in the popup. Adding an url is not the main feature of the plugin. Showing the status of the jobs is.

**Comment by UsYer** [comment]
I just stumbled upon this addon and had the same impression as @wilpjan. I second the suggestion to move the text box to the bottom or to the options.
Otherwise great work!

**Comment by ggirou** [comment]
Let me know what you think, i'm publishing it right now :)

<img width="509" alt="condensed-plugin" src="https://cloud.githubusercontent.com/assets/739916/18291213/fb885f3e-7486-11e6-8e73-0c91bc6af43f.png">

**Comment by UsYer** [comment]
That's much better, thank you very much.
One suggestion for your consideration:
It might be preferable to move the url field right next to the headline, because it currently hides some entries.
Maybe only have the plus button there and it expands to a little popup. Or just move the entire field there and make it smaller.
![jenkinsnotifier](https://cloud.githubusercontent.com/assets/627373/18385867/5bc2744e-7693-11e6-97ab-424d635bb484.png)

**Comment by wilpjan** [comment]
Thank you, that's better than before. But I still prefer to have the "add ur"-feature at the bottom of the scroll list than on the bottom of the popup. Or, as @UsYer recommend, next to the settings as separate popup or textbox.

**Comment by ggirou** [comment]
I finally unfixed the input and it's stay under the list.
But you can now massively edit the urls list in options.

<img width="640" alt="options" src="https://cloud.githubusercontent.com/assets/739916/19162234/5253b890-8bf7-11e6-866d-7eb187497dee.png">

**Comment by wilpjan** [comment]
Perfect! Thank you
