### ISSUE TITLE
View/dashboard sharing

### ISSUE THREAD

**Issue by vkarmarkar** [ggirou/yet-another-jenkins-notifier#17]
Hi @ggirou ,

Really nice tool !!

After creating a view for myself (which consists of jobs from multiple CI machines), how can I share it with my team so everyone can look at a single consolidated view?

Thanks.

**Comment by ggirou** [comment]
Sorry for the late answer, I was quite busy.
It's now possible to massively edit the urls list.
Version 2.3.0 will be available soon ;)

<img width="640" alt="options" src="https://cloud.githubusercontent.com/assets/739916/19162234/5253b890-8bf7-11e6-866d-7eb187497dee.png">

**Comment by vkarmarkar** [comment]
Thanks for the update. However, I don't think my request is addressed in the latest 2.3.0 version. I am looking for a way to share my view with other users so they can also view the status of CI jobs that I have added.

**Comment by ggirou** [comment]
You can share your list of urls to your team so they can configure the extension in their browser. It's a quick-win implementation of what I understood you wanted.
Otherwise, you can install the [remote jobs view plugin](https://wiki.jenkins-ci.org/display/JENKINS/Remote+Jobs+View+Plugin) on one of your jenkins instance. It allows you to create a view with local and remote jobs. So you can share it and update it, every one will have the same view.
I hope it will help you.

**Comment by vkarmarkar** [comment]
Thanks for the tip. Will check the plugin out.
