### ISSUE TITLE
Notification spam on connection loss/recover

### ISSUE THREAD

**Issue by jeanblanchard** [ggirou/yet-another-jenkins-notifier#19]
When the internet connection is lost, I get a "Build is unreachable" notification for every single configured job, and when the connection is recovered, still a bunch of notifications for each job status.

Suggestion:
- Only notify once instead of for each job on connection loss
- Preferably make even that configurable: I actually only want the build failure notifications, I don't want to b spammed when on a shaky wifi.
- Cache the build results somehow, to only notify about the changed jobs when recovering the connection.

**Comment by ggirou** [comment]
Request errors are now handled differently and, for now, there is no more "unreachable" notifications. I don't think I will re-add this kind of notification since it's not the goal of this extension.

BTW, error display slightly changed, details message is now available in a tooltip:
<img width="180" alt="error" src="https://cloud.githubusercontent.com/assets/739916/20349977/11cb19e0-ac0d-11e6-9477-be31022f5121.png">
